let animals = [
    {
      id: "0",
      name: "Alice",
      type: "cat",
      age: 3,
      gender: "female",
    },
    {
      id: "1",
      name: "Jack",
      type: "dog",
      age: 5,
      gender: "male",
    },
    {
      id: "2",
      name: "Cookie",
      type: "parrot",
      age: 1,
      gender: "female",
    },
    {
      id: "3",
      name: "Stevie",
      type: "lion",
      age: 6,
      gender: "male",
    },
    {
      id: "4",
      name: "James",
      type: "parrot",
      age: 2,
      gender: "male",
    },
    {
      id: "5",
      name: "Lily",
      type: "cat",
      age: 1,
      gender: "female",
    },
    {
      id: "6",
      name: "Gary",
      type: "dog",
      age: 2,
      gender: "male",
    },
    {
      id: "7",
      name: "Sarah",
      type: "dog",
      age: 3,
      gender: "female",
    },
    {
      id: "8",
      name: "Bobby",
      type: "cat",
      age: 9,
      gender: "male",
    },
    {
      id: "9",
      name: "Manny",
      type: "lion",
      age: 4,
      gender: "female",
    },
    {
      id: "10",
      name: "Alion",
      type: "lion",
      age: 6,
      gender: "male",
    },
  ];
  export default animals;